services:
#    alphat_shorty.example:
#        class: Alphat\Bundle\ShortyBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    shorty.repository:
        class: Alphat\Bundle\ShortyBundle\Repository\ShortyRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [ Alphat\Bundle\ShortyBundle\Entity\ShortyEntity ]

    shorty.manager:
        class: Alphat\Bundle\ShortyBundle\Manager\ShortyManager
        arguments: ["@alphat_shorty.repository"]

    shorty.create_controller:
        class: Alphat\Bundle\ShortyBundle\Controller\ShortyController

