git:
  depth: 25

language: php

matrix:
    include:
	    - php: 7.2
    fast_finish: true

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist

branches:
  only:
    - master

notifications:
  email:
    -  ybrigant@gmail.com

after_success:
  - travis_retry php vendor/bin/coveralls
  # or enable logging
  - travis_retry php vendor/bin/coveralls -v
