git:
  depth: 25

language: php

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
    fast_finish: true

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist

branches:
  only:
    - master

notifications:
  email:
    -  ybrigant@gmail.com

after_success:
  - travis_retry php vendor/bin/coveralls
  # or enable logging
  - travis_retry php vendor/bin/coveralls -v
