# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    #arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    shorty_repository:
        class: AppBundle\Repository\ShortyRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [ AppBundle\Entity\ShortyEntity ]

    shorty_generated_repository:
        class: AppBundle\Repository\ShortyGeneratedRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [ AppBundle\Entity\ShortyGeneratedEntity ]

    shorty_manager:
        class: AppBundle\Manager\ShortyManager
        arguments: ["@shorty_repository", "@shorty_generated_repository"]
